# Template de colores para Alacritty generado por Hogyoku (TOML)
# Incluye colores extra para mejor contraste y visibilidad
[colors.primary]
background = "#261817"
foreground = "#f6ddda"

[colors.selection]
text = "#690006"
background = "#ffb4ab"

[colors.cursor]
cursor = "#f6ddda"
text = "#261817"

[colors.search.focused_match]
background = "#ffb4ab"
foreground = "#261817"

[colors.search.matches]
background = "#352625"
foreground = "#f6ddda"

[colors.hints.start]
background = "#8e1214"
foreground = "#ffdad6"

[colors.hints.end]
background = "#76322c"
foreground = "#ffdad6"

[colors.normal]
black   = "#e1bfbb"
red     = "#ffb4ab"
green   = "#ffb4ab"
yellow  = "#76322c"
blue    = "#ffb4ab"
magenta = "#ffdad6"
cyan    = "#a88a86"
white   = "#f6ddda"

[colors.bright]
black   = "#a88a86"
red     = "#690005"
green   = "#8e1214"
yellow  = "#ffdad6"
blue    = "#690006"
magenta = "#ffb4ab"
cyan    = "#e1bfbb"
white   = "#f6ddda"

# Puedes agregar más variables si la paleta lo requiere
