# Template de colores para Alacritty generado por Hogyoku (TOML)
# Incluye colores extra para mejor contraste y visibilidad
[colors.primary]
background = "#1f1a1a"
foreground = "#eae0df"

[colors.selection]
text = "#4a2625"
background = "#f2b8b6"

[colors.cursor]
cursor = "#eae0df"
text = "#1f1a1a"

[colors.search.focused_match]
background = "#f2b8b6"
foreground = "#1f1a1a"

[colors.search.matches]
background = "#2e2928"
foreground = "#eae0df"

[colors.hints.start]
background = "#643c3a"
foreground = "#ffdad8"

[colors.hints.end]
background = "#574241"
foreground = "#fbdbd9"

[colors.normal]
black   = "#d5c2c1"
red     = "#ffb4ab"
green   = "#f2b8b6"
yellow  = "#574241"
blue    = "#f2b8b6"
magenta = "#ffdad8"
cyan    = "#9e8d8c"
white   = "#eae0df"

[colors.bright]
black   = "#9e8d8c"
red     = "#690005"
green   = "#643c3a"
yellow  = "#fbdbd9"
blue    = "#4a2625"
magenta = "#f2b8b6"
cyan    = "#d5c2c1"
white   = "#eae0df"

# Puedes agregar más variables si la paleta lo requiere
