# Template de colores para Alacritty generado por Hogyoku (TOML)
# Incluye colores extra para mejor contraste y visibilidad
[colors.primary]
background = "#191c1e"
foreground = "#e1e3e4"

[colors.selection]
text = "#003543"
background = "#8cd0ea"

[colors.cursor]
cursor = "#e1e3e4"
text = "#191c1e"

[colors.search.focused_match]
background = "#8cd0ea"
foreground = "#191c1e"

[colors.search.matches]
background = "#272a2c"
foreground = "#e1e3e4"

[colors.hints.start]
background = "#004e61"
foreground = "#b7eaff"

[colors.hints.end]
background = "#324a54"
foreground = "#cde7f2"

[colors.normal]
black   = "#bfc8cc"
red     = "#ffb4ab"
green   = "#8cd0ea"
yellow  = "#324a54"
blue    = "#8cd0ea"
magenta = "#b7eaff"
cyan    = "#899296"
white   = "#e1e3e4"

[colors.bright]
black   = "#899296"
red     = "#690005"
green   = "#004e61"
yellow  = "#cde7f2"
blue    = "#003543"
magenta = "#8cd0ea"
cyan    = "#bfc8cc"
white   = "#e1e3e4"

# Puedes agregar más variables si la paleta lo requiere
