# Template de colores para Alacritty generado por Hogyoku (TOML)
# Incluye colores extra para mejor contraste y visibilidad
[colors.primary]
background = "#1b1c1b"
foreground = "#e4e2e1"

[colors.selection]
text = "#223430"
background = "#b6cbc5"

[colors.cursor]
cursor = "#e4e2e1"
text = "#1b1c1b"

[colors.search.focused_match]
background = "#b6cbc5"
foreground = "#1b1c1b"

[colors.search.matches]
background = "#292a29"
foreground = "#e4e2e1"

[colors.hints.start]
background = "#384a46"
foreground = "#d2e7e0"

[colors.hints.end]
background = "#414846"
foreground = "#dde4e1"

[colors.normal]
black   = "#c2c8c5"
red     = "#ffb4ab"
green   = "#b6cbc5"
yellow  = "#414846"
blue    = "#b6cbc5"
magenta = "#d2e7e0"
cyan    = "#8c928f"
white   = "#e4e2e1"

[colors.bright]
black   = "#8c928f"
red     = "#690005"
green   = "#384a46"
yellow  = "#dde4e1"
blue    = "#223430"
magenta = "#b6cbc5"
cyan    = "#c2c8c5"
white   = "#e4e2e1"

# Puedes agregar más variables si la paleta lo requiere
